# Generated by Django 5.2.8 on 2025-11-28 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meat_shop', '0002_alter_product_category_remove_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за кг'),
        ),
    ]
