# Generated by Django 5.2.8 on 2025-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meat_shop', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта при получении'), ('online', 'Онлайн-оплата')], default='cash', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
